language: php
php:
  - '7.3'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE todo_list;'
script:
  - composer install
  - bin/console doctrine:schema:create
  - vendor/bin/simple-phpunit

